@startuml

[App]
[ProductsC]
[ReviewC]
[VotesC]
[AuthenticationC]
[ProductsQ]
[ReviewQ]
[VotesQ]
[AuthenticationQ]
[ProductsC_n]
[ReviewC_n]
[VotesC_n]
[AuthenticationC_n]
[ProductsQ_n]
[ReviewQ_n]
[VotesQ_n]
[AuthenticationQ_n]

 App --(0 ProductsC
 App --(0 ReviewC
 App --(0 VotesC
 App --(0 AuthenticationC


 App --(0 ProductsQ
 App --(0 ReviewQ
 App --(0 VotesQ
 App --(0 AuthenticationQ

 App --(0 ProductsC_n
 App --(0 ReviewC_n
 App--(0 VotesC_n
 App --(0 AuthenticationC_n

 App --(0 ProductsQ_n
 App --(0 ReviewQ_n
 App --(0 VotesQ_n
 App --(0 AuthenticationQ_n



@enduml
