@startuml
'https://plantuml.com/sequence-diagram

title Obtain the catalog of products
autoactivate on
autonumber

actor "Client" as client
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository
participant ":ProductCatalog" as details

activate client

client -> controller : GET /products
controller -> service : productService.findAllCatalog()
service -> repository: productRepo.findAllCatalog()
repository -> repository: getAll()
repository -> repository: list
loop for each 'product' in 'list'
    repository -> details**: new(product)
    details --> repository: productCatalog
    repository --> repository: listOfProductCatalog.add(productCatalog)
end loop
repository --> service: listOfProductCatalog
service --> controller: listOfProductCatalog
controller --> client: listOfProductCatalog & 200

@enduml