@startuml
'https://plantuml.com/sequence-diagram

title Obtain the details of a product
autoactivate on
autonumber

actor "Client" as client
participant ":ProductQ_n" as productQ
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository
participant ":ProductDetails" as details

activate client

client -> productQ: GET /products/{sku}
productQ -> controller: GET /products/{sku}
controller -> service : productService.findBySku(sku)
service -> repository: productRepo.findBySuk(sku)

repository --> service: product





service -> details**: new(product)
details --> service: productDetails
service --> controller: productDetails
controller --> productQ: productDetails
productQ --> client: productDetails


@enduml
