@startuml
'https://plantuml.com/sequence-diagram

title Obtain the details of a product
autoactivate on
autonumber

actor "Client" as client
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository

participant "ProductInstance" as instance
activate client

client -> controller: GET /products/{sku}
controller -> service : productService.findBySku(sku)
service -> repository: productRepo.findBySuk(sku)
loop for each 'instance' in instances
 repository -> instance : GET /products/{sku}
 instance --> repository: listOfProductCatalog
end loop
repository --> service: productDetails
service --> controller: productDetails
controller --> client: productDetails


@enduml
