@startuml
'https://plantuml.com/sequence-diagram

title Obtain the details of a product
autoactivate on
autonumber

actor "Client" as client
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository
participant "requestService:RequestService" as request
participant ":ProductInstance" as instance
participant ":ProductDetails" as details

activate client

client -> controller: GET /products/{sku}
controller -> service : productService.findBySku(sku)
service -> repository: productRepo.findBySuk(sku)
alt success case
repository --> service: product
else product == null
service -> request:retrieveProductFromApi(sku)
request -> instance: GET /products/{sku}
instance --> request: product & 200
request --> service: product
end

service -> details**: new(product)
details --> service: productDetails
service --> controller: productDetails & 200
controller --> client: productDetails & 200


@enduml
