@startuml
'https://plantuml.com/sequence-diagram

title Search the catalog of products by product name or bar code
autoactivate on
autonumber

actor "Client" as client
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository
participant ":ProductDetails" as details
participant "product:Product" as product

activate client

client -> controller: GET /products/search/{skuOrName}
controller -> service : productService.findByNameOrSuk(skuOrName)
service -> repository: productRepo.findByNameOrSuk(skuOrName)

loop for each 'product' in 'list'
    repository -> details**: new(product)
    details --> repository: productDetails
    repository --> repository: listOfProductDetails.add(productDetails)
end loop
repository --> service: listOfProductDetails
service --> controller: listOfProductDetails
controller --> client: listOfProductDetails


@enduml