@startuml
'https://plantuml.com/sequence-diagram


autoactivate on
autonumber

actor "Client" as client
participant "ProductsController" as controller
participant "productService:ProductsService" as service
participant "productRepo:ProductsRepository" as repository
participant ":ProductDetails" as details
participant "product:Product" as product

activate client

client -> controller: GET /products/search/{skuOrName}
controller -> service : productService.findByNameOrSuk(skuOrName)
service -> repository: productRepo.findByNameOrSuk(skuOrName)

loop for each 'product' in 'list'
    repository -> product: getSku()
    product --> repository: sku
    repository -> product: getName()
    product --> repository: name
    repository -> product: getDescription()
    product --> repository: description
    repository -> product: getImages()
    product --> repository: images
    repository -> details**: new(sku,name,description,images)
    details --> repository: productDetails
    repository --> repository: listOfProductDetails.add(productDetails)
end loop
repository --> service: listOfProductDetails
service --> controller: listOfProductDetails
controller --> client: listOfProductDetails


@enduml