@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "ACME" as User
participant "ReviewController" as Ctrl
participant "reviewService:ReviewService" as Svc
participant "productRepo:ProductRepository" as repository
participant "requestService:RequestService" as request
participant ":ProductInstance" as instance
participant "review:Review" as review
participant "reviewRepo:ReviewRepository" as Repo

activate User

User -> Ctrl : POST/reviews{sku}

Ctrl -> Svc : create(reviewDTO, sku, request)
Svc -> repository : productRepo.findBySkuProduct(sku);
alt success case
repository --> Svc : product
else product == null
Svc -> request:retrieveProductFromApi(sku)
request -> instance: GET /products/{sku}
instance --> request: product
request --> Svc: product
end
Svc -> Svc: jwt = parseJwt(request)
Svc -> request: makeRequestToAuthentication(jwt)
request -> instance: GET /auth/search/{jwt}
instance --> request: user
request --> Svc: user
Svc -> review** : create(reviewDTO,sku,user.getUserId)
review --> Svc :  review
Svc -> Repo : reviewRepo.save(review)
Repo --> Svc : ok
Svc --> Ctrl : ok
Ctrl --> User : ok

@enduml