@startuml
'https://plantuml.com/sequence-diagram
title Obtain the reviews of a product
autoactivate on
autonumber

actor "Client" as Client
participant ":ReviewQ_n" as reviewQ
participant "ReviewController" as CtrlR
participant "reviewService:ReviewService" as SvcR
participant "reviewRepo:ReviewRepository" as RepoR

activate Client

Client -> reviewQ : GET/reviews{SKU}
reviewQ -> CtrlR: GET/reviews{SKU}
CtrlR -> SvcR : reviewService.findAllReviews(sku)
SvcR -> RepoR: reviewRepo.findAll(sku)
RepoR --> SvcR: reviews
SvcR --> CtrlR: reviews
CtrlR --> reviewQ: reviews
reviewQ -> Client: reviews



@enduml
