@startuml
'https://plantuml.com/sequence-diagram
title Obtain the reviews of a product
autoactivate on
autonumber

actor "Client" as Client

participant "ReviewController" as CtrlR
participant "reviewService:ReviewService" as SvcR
participant "productRepo:ProductRepository" as RepoP
participant "reviewRepo:ReviewRepository" as RepoR

activate Client

Client -> CtrlR : GET/reviews{SKU}
CtrlR -> SvcR : reviewService.findAllReviews(sku)
SvcR -> RepoR: reviewRepo.findAll(sku)
RepoR --> SvcR: reviews
SvcR --> CtrlR: reviews
CtrlR --> "Client": reviews



@enduml