@startuml
'https://plantuml.com/sequence-diagram

title Vote for a review
autoactivate on
autonumber

actor "Client" as User
participant "VotesController" as Ctrl
participant "votesService:VotesService" as service
participant "voteRepository:VoteRepository" as repo
participant "requestService:RequestService" as request
participant ":ReviewInstance" as instance
participant ":AuthInstance" as instanceAuth

participant "vote:Vote" as vote




activate User
User -> Ctrl : POST /votes/{idReview}
Ctrl -> service : service.create(resource,idReview,idUser);
service -> request: parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user

service -> request:retrieveReviewFromApi(reviewId)
request -> instance: GET /reviews/search/{reviewId}
instance --> request: review
request --> service: review

service -> vote**: new(resource.getVote(),user.getId,reviewId)
vote --> service: vote
service -> repo: save(vote)
repo --> service: ok
service --> Ctrl: ok
Ctrl --> User: ok

@enduml
