@startuml
'https://plantuml.com/sequence-diagram

title Withdraw one of my reviews
autoactivate on
autonumber




actor "Client" as User



reviewC_n -> broker: subscribe "Vote.deleted"
reviewQ -> broker: subscribe "Vote.deleted"
reviewQ_n -> broker: subscribe "Vote.deleted"
voteC -> broker: subscribe "Vote.deleted"
voteC_n -> broker: subscribe "Vote.deleted"

participant ":ReviewC" as reviewC
participant ":ReviewC_n" as reviewC_n
participant ":ReviewQ" as reviewQ
participant ":ReviewQ_n" as reviewQ_n
participant ":VoteC" as voteC
participant ":VoteC_n" as voteC_n

participant "ReviewController" as Ctrl
participant "reviewService:ReviewService" as service
participant "reviewRepositoryReviewRepository" as repo
participant "requestService:RequestService" as request
participant ":ReviewInstance" as instance
participant ":AuthInstance" as instanceAuth

participant ":MessageBroker" as broker




activate User
User -> reviewC : DELETE review/{idReview}
reviewC -> Ctrl: DELETE review/{idReview}
Ctrl -> service : reviewService.deleteById(idReview)

service -> request : parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user

service -> request:retrieveProductFromApi(sku)
request -> instance: GET /products/{sku}
instance --> request: product
request --> service: product
service -> repo: reviewRepo.deleteIdReview(idReview))
repo -> broker: publish "Vote.deleted, {Vote}"

reviewC_n <- broker: notify "Vote.deleted"
reviewQ <- broker: notify "Vote.deleted"
reviewQ_n <- broker: notify "Vote.deleted"
voteC <- broker: notify "Vote.deleted"
voteC_n <- broker: notify "Vote.deleted"

repo --> service: ok
service --> Ctrl: ok
Ctrl --> reviewC: ok
reviewC --> User: ok



@enduml
