@startuml
'https://plantuml.com/sequence-diagram

title Withdraw one of my reviews
autoactivate on
autonumber




actor "Client" as User



reviewC_n -> broker: subscribe "Review.deleted"
reviewQ -> broker: subscribe "Review.deleted"
reviewQ_n -> broker: subscribe "Review.deleted"
voteC -> broker: subscribe "Review.deleted"
voteC_n -> broker: subscribe "Review.deleted"

participant ":ReviewC" as reviewC
participant ":ReviewC_n" as reviewC_n
participant ":ReviewQ" as reviewQ
participant ":ReviewQ_n" as reviewQ_n
participant ":VoteC" as voteC
participant ":VoteC_n" as voteC_n

participant "ReviewController" as Ctrl
participant "reviewService:ReviewService" as service
participant "reviewRepositoryReviewRepository" as repo
participant "requestService:RequestService" as request
participant ":ReviewInstance" as instance
participant ":AuthInstance" as instanceAuth

participant ":MessageBroker" as broker




activate User
User -> reviewC : DELETE review/{idReview}
reviewC -> Ctrl: DELETE review/{idReview}
Ctrl -> service : reviewService.deleteById(idReview)

service -> request : parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user

service -> request:retrieveProductFromApi(sku)
request -> instance: GET /products/{sku}
instance --> request: product
request --> service: product
service -> repo: reviewRepo.deleteIdReview(idReview))
repo -> broker: publish "Review.deleted, {Review}"

reviewC_n <- broker: notify "Review.deleted, {Review}"
reviewC_n -> reviewC_n: delete(Review)
reviewQ <- broker: notify "Review.deleted, {Review}"
reviewQ -> reviewQ: delete(Review)
reviewQ_n <- broker: notify "Review.deleted, {Review}"
reviewQ_n -> reviewQ_n: delete(Review)
voteC <- broker: notify "Review.deleted, {Review}"
voteC -> voteC: delete(Review)
voteC_n <- broker: notify "Review.deleted, {Review}"
voteC_n -> voteC_n: delete(Review)

repo --> service: ok
service --> Ctrl: ok
Ctrl --> reviewC: ok
reviewC --> User: ok



@enduml
