@startuml
'https://plantuml.com/sequence-diagram

title Obtain the reviews of a product, sorted by number of votes and reverse chronological publishing date
autoactivate on
autonumber

actor "Client" as Client
participant "VotesController" as Ctrl
participant "voteService:VoteService" as Svc
participant "reviewRepository:ReviewRepository" as reviewRepository
participant "requestService:RequestService" as request
participant ":ProductInstance" as instance

activate Client

Client -> Ctrl : GET /order/{SKU}
Ctrl -> Svc : voteService.orderAllReviewsByVotes(sku)
Svc -> request: getStatusCodeOfProduct(sku)
request -> instance: GET /products/{sku}
instance --> request: ok
request --> Svc: ok
Svc -> reviewRepository: reviewRepository.orderByVotes(sku)
reviewRepository --> Svc: reviews
Svc --> Ctrl: reviews
Ctrl --> Client: reviews

@enduml
