@startuml
'https://plantuml.com/sequence-diagram

title Obtain the reviews of a product, sorted by number of votes and reverse chronological publishing date
autoactivate on
autonumber

actor "Client" as Client
participant ":VotesC_n" as votesC
participant "VotesController" as Ctrl
participant "voteService:VoteService" as Svc
participant "reviewRepository:ReviewRepository" as reviewRepository
participant ":ReviewRepository" as productRepository

activate Client

Client -> votesC : GET /order/{SKU}
votesC -> Ctrl: GET /order/{SKU}
Ctrl -> Svc : voteService.orderAllReviewsByVotes(sku)
Svc -> productRepository: findBySku(sku)
productRepository --> Svc: ok
Svc -> reviewRepository: reviewRepository.orderByVotes(sku)
reviewRepository --> Svc: reviews
Svc --> Ctrl: reviews
Ctrl --> votesC: reviews
votesC --> Client: reviews

@enduml
