@startuml
'https://plantuml.com/sequence-diagram

title Obtain all pending reviews
autoactivate on
autonumber

actor "Client" as client
participant "ModeratorController" as controller
participant "reviewService:ReviewService" as service
participant "reviewRepository:ReviewRepository" as repository
participant ":ReviewDTO" as reviewUser
participant "requestService:RequestService" as request
participant ":AuthInstance" as instanceAuth

activate client

client -> controller: GET /moderator/reviews
controller -> service : reviewService.findAllReviewsPending()
service -> request : parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user
alt user.getRoles = "MODERATOR"
service -> repository: reviewRepository.findAllPending();
repository --> service: reviews
loop for each "review" in reviews
    service -> reviewUser**: new ReviewUser(review)
    reviewUser --> service: reviewUser
    service -> service: reviewsPending.add(reviewUser);
end loop
end
service --> controller: reviewsPending
controller --> client: reviewsPending

@enduml