@startuml
'https://plantuml.com/sequence-diagram

title Obtain all pending reviews
autoactivate on
autonumber

actor "Client" as client
participant ":ReviewQ_n" as reviewQ
participant "ModeratorController" as controller
participant "reviewService:ReviewService" as service
participant "reviewRepository:ReviewRepository" as repository
participant ":ReviewDTO" as reviewUser
participant ":JWTRepository" as jwtRepository

activate client

client -> reviewQ: GET /moderator/reviews
reviewQ -> controller: GET /moderator/reviews
controller -> service : reviewService.findAllReviewsPending()
service --> service : parseJwt(request)
service -> jwtRepository: findByJWT(jwt)
jwtRepository --> service: user
alt user.getRoles = "MODERATOR"
service -> repository: reviewRepository.findAllPending();
repository --> service: reviews
loop for each "review" in reviews
    service -> reviewUser**: new ReviewUser(review)
    reviewUser --> service: reviewUser
    service -> service: reviewsPending.add(reviewUser);
end loop
end
service --> controller: reviewsPending
controller --> reviewQ: reviewsPending
reviewQ --> client: reviewsPending

@enduml
