@startuml
'https://plantuml.com/sequence-diagram

title Approve or reject a pending review
autoactivate on
autonumber

actor "Client" as client
participant "ModeratorController" as controller
participant "reviewService:ReviewService" as service
participant "reviewRepository:ReviewRepository" as repository
participant "requestService:RequestService" as request
participant ":AuthInstance" as instanceAuth

activate client

client -> controller: PUT /moderator/review/{idReview}
controller -> service : reviewService.changeStatus(idReview,resource)

service -> request : parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user
alt user.getRoles = "MODERATOR"
    service -> repository: reviewRepository.updateReview(resource,idReview)
    repository --> service: ok
end


service -> controller: review
controller -> client: review

@enduml