@startuml
'https://plantuml.com/sequence-diagram

title Obtain all my reviews including their status
autoactivate on
autonumber

actor "Client" as Client
participant ":ReviewQ_n" as reviewQ
participant "ReviewController" as Ctrl
participant "reviewService:ReviewService" as service
participant "reviewRepository:ReviewRepository" as Repo
participant ":ReviewDTO" as reviewDTO
participant ":JWTRepository" as jwtRepository

activate Client

Client -> reviewQ : GET /reviews/user/{idUser}
reviewQ -> Ctrl: GET /reviews/user/{idUser}
Ctrl -> service : reviewService.findAllReviewsByUser(idUser,request)
service --> service : parseJwt(request)
service -> jwtRepository: findByJWT(jwt)
jwtRepository --> service: user
service -> Repo: reviewRepository.findAllReviewsByUser(user.getId())
Repo --> service: reviews
loop for each "review" in reviews

    service -> reviewDTO**: new ReviewDTO(review))
    reviewDTO --> service: reviewDTO
    service -> service: reviewsUser.add(reviewDTO);
end loop
service --> Ctrl: reviewsDTO
Ctrl --> reviewQ: list of reviews
reviewQ -> Client: list of reviews

@enduml
