@startuml
'https://plantuml.com/sequence-diagram


autoactivate on
autonumber

actor "Client" as Client
participant "ReviewController" as Ctrl
participant "reviewService:ReviewService" as service
participant "reviewRepository:ReviewRepository" as Repo
participant ":ReviewDTO" as reviewDTO
participant "requestService:RequestService" as request
participant ":AuthInstance" as instanceAuth

activate Client

Client -> Ctrl : GET /reviews/user/{idUser}
Ctrl -> service : reviewService.findAllReviewsByUser(idUser,request)
service -> request : parseJwt(request)
request --> service: jwt
service -> request: makeRequestToAuthentication(jwt)
request -> instanceAuth: GET /auth/search/{jwt}
instanceAuth --> request: user
request --> service: user
service -> Repo: reviewRepository.findAllReviewsByUser(user.getId())
Repo --> service: reviews
loop for each "review" in reviews

    service -> reviewDTO**: new ReviewDTO(review))
    reviewDTO --> service: reviewDTO
    service -> service: reviewsUser.add(reviewDTO);
end loop
service --> Ctrl: reviewsDTO
Ctrl --> Client: list of reviews

@enduml