@startuml
'https://plantuml.com/sequence-diagram

title Obtain the aggregated rating of a product

autoactivate on
autonumber

actor "Client" as Client
participant "ReviewController" as Ctrl
participant "reviewService:reviewService" as Svc
participant "reviewRepository:reviewRepository" as Repo
participant ":AggregateRating" as aggregateRating

activate Client

Client -> Ctrl : GET/reviews/{sku}/rating
Ctrl -> Svc : productService.findAllRates(sku)
Svc -> Repo: productRepository.findAllApprovedReviewsBySku(sku)
Repo --> Svc: reviews
Svc -> aggregateRating**: new ReviewDTO(review))
aggregateRating --> Svc: rating
Svc --> Ctrl: rating
Ctrl --> Client: rating





@enduml
